### ISSUE TITLE
error when compile

### ISSUE THREAD

**Issue by mehranexpert** [Tinram/MySQL-Brute#1]
```
# make
make: mysql_config: Command not found
make: mysql_config: Command not found
gcc mysqlbrute.c -o mysqlbrute -Ofast -Wall -Wextra -Wuninitialized -Wunused -Werror -std=gnu99 -s  
mysqlbrute.c:30:19: fatal error: mysql.h: No such file or directory
 #include <mysql.h>
                   ^
compilation terminated.
makefile:12: recipe for target 'mysqlbrute' failed
make: *** [mysqlbrute] Error 1

```

**Comment by Tinram** [comment]
I think you must be missing the MySQL development libraries from the machine you are using.

If `whereis mysql_config` returns nothing, then you are missing *mysql_config*

(With the above, I get the output: */usr/bin/mysql_config /usr/share/man/man1/mysql_config.1.gz*)

*mysql_config* should be located in *libmysqlclient-dev*

These posts confirm my memory:

[Ubuntu mysql_config](https://packages.ubuntu.com/search?suite=precise&mode=filename&searchon=contents&keywords=mysql_config)

[Stackoverflow post](https://stackoverflow.com/questions/7475223/mysql-config-not-found-when-installing-mysqldb-python-interface)

For Debian-based distros, do:

    sudo apt-get install libmysqlclient-dev

and then try `make` again.

I did document *libmysqlclient-dev* in the 'Build' section of the MySQL Brute *README.md*
(But yes, MySQL Brute probably needs a *configure.sh* script to look for dependencies before running make.)

Alternatively, to avoid dependencies, you could just download the MySQL Brute binaries:

[releases](https://github.com/Tinram/MySQL-Brute/releases)

although I appreciate that you may want to build from source.

Hope this helps you.

**Comment by h0ek** [comment]
Small update for eg. kali users.

Install libmariadb-dev-compat and libmariadb-dev instead of libmysqlclient-dev.
It was replaced some time ago.

`apt install libmariadb-dev-compat libmariadb-dev`

**Comment by Tinram** [comment]
Thank you!
I have added a makefile for MariaDB and updated the ReadMe.
